#!/bin/bash

# 垃圾清理命令，可根据需要自行修改
clean_commands="apt-get clean
journalctl --vacuum-size=5M
echo > /var/log/syslog
echo > /var/log/syslog.1
echo > /var/log/mail.log.1
echo > /var/log/mail.info.1
echo > /var/log/mail.warn.1
echo > /var/log/mail.err.1
echo > /var/log/mail.log
echo > /var/log/mail.info
echo > /var/log/mail.warn
echo > /var/log/mail.err
echo \"清理垃圾完成\""

# 更改软件源为阿里源并更新必要的软件包
echo "更改软件源为阿里源"
echo "deb https://mirrors.aliyun.com/debian/ bullseye main non-free contrib" > /etc/apt/sources.list
echo "deb-src https://mirrors.aliyun.com/debian/ bullseye main non-free contrib" >> /etc/apt/sources.list
echo "deb https://mirrors.aliyun.com/debian-security/ bullseye-security main" >> /etc/apt/sources.list
echo "deb-src https://mirrors.aliyun.com/debian-security/ bullseye-security main" >> /etc/apt/sources.list
echo "deb https://mirrors.aliyun.com/debian/ bullseye-updates main non-free contrib" >> /etc/apt/sources.list
echo "deb-src https://mirrors.aliyun.com/debian/ bullseye-updates main non-free contrib" >> /etc/apt/sources.list
echo "deb https://mirrors.aliyun.com/debian/ bullseye-backports main non-free contrib" >> /etc/apt/sources.list
echo "deb-src https://mirrors.aliyun.com/debian/ bullseye-backports main non-free contrib" >> /etc/apt/sources.list
echo "deb http://deb.debian.org/debian buster main" >> /etc/apt/sources.list
echo "deb-src http://deb.debian.org/debian buster main" >> /etc/apt/sources.list
#echo none > /sys/class/leds/green:internet/trigger && sleep 1
#echo 255 > /sys/class/leds/green:internet/brightness && sleep 1
apt update && sleep 1
apt upgrade -y && sleep 2
# 安装推荐软件包
echo "安装推荐软件包"
apt-get install zip byobu cron btrfs-progs rsync preload zsh -y && sleep 6
sleep 1
apt-get autoclean -y
# 启用 byobu和zsh
byobu-enable
sleep 1
sudo sh -c 'echo /usr/bin/zsh >> /etc/shells'
sleep 1
chsh -s /usr/bin/zsh
cat /etc/shells

# 清理垃圾并压缩系统
echo "正在清理垃圾..."
byobu-enable
eval "$clean_commands" && sleep 2
curl -sSL https://github.com/xiezh123/132/raw/main/1 -o /usr/local/bin/z && sudo chmod +x /usr/local/bin/z
if [[ $(grep -c btrfs /proc/mounts) -gt 0 ]]; then
  echo "正在压缩系统..."
  btrfs filesystem defragment -r -v -czstd / && sleep 6
else
  echo "系统文件不是btrfs，取消执行压缩系统命令"
fi

# 重启系统
echo "重启以确保稳定性..."
echo -e "\033[33;32m如需执行脚本，可以在终端输入：z\033[0m"
eval "$clean_commands" && sleep 1
echo timer > /sys/class/leds/green\:internet/trigger && sleep 1
sudo rm /root/Quick/output.log
sleep 1
#/sbin/reboot
