#!/bin/bash

# 提示用户确认操作
echo "在执行脚本前，最好将内存卡格式化成和系统一样的文件格式，然后允许以读写模式挂载"
read -p "是否继续执行？（y/n）" choice

# 如果用户选择 "n"，退出脚本
if [[ $choice =~ ^[Nn]$ ]]; then
  echo "脚本已退出。"
  exit
fi

# 获取用户输入的目录
while true; do
  echo -n "请输入想要复制到的目录路径，比如/mnt: "
  read target_directory

  # 检查输入的目录是否存在
  if [ ! -d "$target_directory" ]; then
    echo "输入的目录路径不存在，请重新输入。"
  else
    break
  fi
done

# 停止 Docker 服务
echo "正在停止 Docker 服务..."
sudo service docker stop
echo "Docker 服务已停止。"

# 取消 Docker 开机自启服务
echo "正在取消 Docker 开机自启服务..."
sleep 2
sudo systemctl disable docker
echo "已取消 Docker 开机自启服务。"

# 挂载目标磁盘
echo "正在挂载目标磁盘..."
sleep 2
sudo mount /dev/sda1 /mnt && sleep 2
sudo mount -o remount,rw /dev/sda1 /mnt && sleep 3
echo "目标磁盘已挂载。"

# 复制 Docker 数据目录到目标目录
echo "正在复制 Docker 数据目录到目标目录..."
sleep 2
sudo rsync -a --progress /var/lib/docker/ "$target_directory/docker"
echo "Docker 数据目录已成功复制到目标目录。"

# 删除原有 Docker 数据目录
echo "正在删除原有 Docker 数据目录..."
sudo rm -rf /var/lib/docker
echo "原有 Docker 数据目录已成功删除。"

# 创建软链接
echo "正在创建软链接..."
sleep 1
sudo ln -s "$target_directory/docker" /var/lib/
echo "软链接已成功创建。"

# 启动 Docker 服务
echo "正在启动 Docker 服务..."
sleep 3
sudo service docker start
echo "Docker 服务已成功启动。"

# 等待 Docker 启动
echo "正在检查 Docker 服务状态..."
sleep 3
sudo systemctl status docker
echo "请查看Docker服务是否正常。"
sudo rm /root/3
